name: Test

on:
  watch:
    types: [started]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      run: |
        sudo apt-get -y install file curl jq
        mkdir -p /opt/test
        touch /opt/test/abc.txt
        ls /opt/test

    - name: Upload to release
      uses: 1005789164/action-release@1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        gzip: false
        files: >
          /opt/test/*.txt
        allow_override: true